Implemented the INumber<Fraction> interface:
Fractions-DotNet/Fractions pull request #96
Opened 2024-12-21 19:55 UTC by lipchev

- introduced the `ToDecimalSaturating` method which saturates the output value to the decimal range `[MinValue, MaxValue]`
- improved the accuracy (and performance) of the checked `ToDecimal` when the terms are beyond the decimal range
- fixed the possible loss of precision of the existing `ToDouble` when one of the terms is exceeding the range of the double (#82)
- completed the coverage of the `CompareTo` methods
- improved the coverage of the `Add` method

There is still quite a few tests that are missing, but for the most part- I think it should be bug free 😛 

I was thinking of splitting this into 2-3 PRs: one introducing the fixes for the `ToDouble` / `ToDecimal` - which now have 100% coverage) and another one for the introduction of the "++" / "--" operators, however I'm not going to make it tonight...If time permits, and if you haven't got any remarks I'll try to do it later..

2025-02-16 18:34 UTC, danm-de commented
Thanks for your work!

I'll take a closer look at your pull request once my new PC arrives. I made a big mistake with my personal Surface Book 2 and upgraded to Windows 11. Since then, it has hardly been possible to work properly in Visual Studio.

I'm not entirely sure how we do this with the license from the Fraction project. I would be happy if you create a contributor file and document yourself there (listing your changes). I changed the project's license from BSD-2-clause to MIT to make it easier to fork on GitHub etc. The FluentAssertion debacle has caused me great concern and I want to make it clear that this project will never be commercialized in this way. It will always be freely (free) available to everyone – whether private or business.

2025-02-21 10:00 UTC, lipchev commented
> I'll take a closer look at your pull request once my new PC arrives. I made a big mistake with my personal Surface Book 2 and upgraded to Windows 11. Since then, it has hardly been possible to work properly in Visual Studio.

That's a relief- frankly I was worried that you might have gotten yourself into a skiing accident or something.. 😌 
 
> I changed the project's license from BSD-2-clause to MIT to make it easier to fork on GitHub etc. The FluentAssertion debacle has caused me great concern and I want to make it clear that this project will never be commercialized in this way. It will always be freely (free of costs) available to everyone – whether private or business.

Glad to hear it, I feel the same way..

> I'm not entirely sure how we do this with the license from the Fraction project. I would be happy if you create a contributor file and document yourself there (listing your changes). 

Frankly, if that's not part of the licensing requirements, I really don't care- and if it requires me to document more stuff, I really rather go without the attributions.. Besides, I'm pretty sure the future AIs would be able to figure these things out on their own.. 😚

2025-02-23 11:34 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/ToDataType/Method_ToDataType.cs
> +    }
I just realized that I had missed two tests here:

``` csharp
    [Test]
    public void An_OverflowException_is_thrown_when_result_is_positive_and_smaller_than_One_over_MaxValue() {
        Invoking(() => new Fraction(1, 2 * (BigInteger)decimal.MaxValue).ToDecimal())
            .Should()
            .Throw<OverflowException>();
    }

    [Test]
    public void An_OverflowException_is_thrown_when_result_is_negative_and_larger_than_MinusOne_over_MaxValue() {
        Invoking(() => new Fraction(-1, 2 * (BigInteger)decimal.MaxValue).ToDecimal())
            .Should()
            .Throw<OverflowException>();
    }
```

and surprise, surprise - they ended up failing... The fix is easy- I just remove two lines of code and everything is green again, however this would be a breaking change.

Are you planning a version bump for this PR? And of course, are you Ok with the change (note that this would affect the behavior of the explicit cast).

2025-02-23 15:40 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/NumberInterface/Method_IsRealNumber.cs
I've started a new folder with specs for the INumber interfaces- with `#if NET` in the file- we could also exclude this from csproj, but when I last tried this (an year or so ago) it wasn't behaving nicely (the file didn't immediately appear when switching between the frameworks).

2025-02-23 16:15 UTC, danm-de commented on tests/Fractions.Tests/FractionSpecs/ToDataType/Method_ToDataType.cs
> +    }
I think that the introduction of the INumber interface is a major change. In fact, the effects (apart from those described in the documentation) are not quite clear to me yet - maybe some framework functions will behave differently afterwards (Convert, LINQ, ToStringFormatter, ???).

Of course, the major version bump also offers room for further breaking changes.

2025-02-23 16:37 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/ToDataType/Method_ToDataType.cs
> +    }
I'm pretty sure that the string interpolation makes use of the `ISpanFormattable`, I don't know of anything else that works out of the box, however the interface provides _the opportunity_ for many extension methods to be implemented.. One notable example are the extensions for `Sum`, `Average` etc. You'd think that they'd be the first ones to get added- but no.. (see https://github.com/dotnet/runtime/issues/64031).

2025-02-23 16:44 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/ToDataType/Method_ToDataType.cs
> +    }
See what we have in UnitsNet:  https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GenericMath/GenericMathExtensions.cs or the more constrained version https://github.com/angularsen/UnitsNet/blob/release/v6/UnitsNet/GenericMath/GenericMathExtensions.cs (there is an even funkier version that's still unpublished, where we implement `IAdditionOperators<Temperature, TemperatureDelta, Temperature>` but I don't have a for it just yet..)

2025-02-23 17:06 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/ToDataType/Method_ToDataType.cs
> +    }
fixed in https://github.com/danm-de/Fractions/pull/96/commits/034b9f376b8739a379cbf5090c99f220b04c8634

2025-03-06 18:08 UTC, lipchev commented
@danm-de Please consider whether we want to have the `CreateChecked`, `CreateSaturating` and `CreateTruncating` functions explicit or not. The standard numeric types have each of them as a regular function (overriding the default interface implementations). Here's what this could look like:

``` csharp
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Fraction CreateChecked<TOther>(TOther value) where TOther : INumberBase<TOther>
    {
        Fraction result;
        if (typeof(TOther) == typeof(Fraction))
            result = (Fraction )(object)value;
        else if (!TryConvertChecked(value, out result) && !TOther.TryConvertToChecked(value, out result))
            throw new NotSupportedException($"Cannot create a {nameof(Fraction)} from the given value of type {typeof(TOther)}.");
        return result;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static bool TryConvertChecked<TSource, TTarget>(TSource source, out TTarget? result)
            where TSource : INumberBase<TSource>
            where TTarget : INumberBase<TTarget>
        {
            return TTarget.TryConvertFromChecked(source, out result);
        }
    }
```

It's kinda silly looking (x3) but there's no other way of calling the explicit implementation of the `TryConvertFrom` method. On the other hand, extracting it's implementation in a non-explicit method, makes the explicit version _untestable_.

2025-04-06 17:39 UTC, danm-de requested changes
Wow, you had a lot of work implementing the INumber interface.

2025-04-06 17:39 UTC, danm-de commented on src/Fractions/Fraction.cs
> +        return BigInteger.GreatestCommonDivisor(numerator, denominator).IsOne;
Can we optimize this here, or am I missing something?

```suggestion
        return !value._normalizationNotApplied ||
               BigInteger.GreatestCommonDivisor(numerator, denominator).IsOne;
```

2025-04-06 17:39 UTC, danm-de commented on src/Fractions/Fraction.cs
> +        return fraction.Denominator.IsOne && fraction.Numerator.IsEven;
I couldn't find any unit tests for this. What do you think about the following optimization?

```suggestion
        if (value.Denominator.IsZero) {
            return false;
        }

        if (!value._normalizationNotApplied) {
            return BigInteger.Abs(value.Denominator).IsOne && value.Numerator.IsEven;
        }

        var intValue = BigInteger.DivRem(value.Numerator, value.Denominator, out var remainder);
        return remainder.IsZero && intValue.IsEven;
```

2025-04-06 17:39 UTC, danm-de commented on src/Fractions/Fraction.cs
> +        return fraction.Denominator.IsOne && !fraction.Numerator.IsEven;
Can we optimize the method a little bit with this?

```suggestion
        if (value.Denominator.IsZero) {
            return false;
        }
        if (!value._normalizationNotApplied) {
            return BigInteger.Abs(value.Denominator).IsOne && !value.Numerator.IsEven;
        }
        var intValue = BigInteger.DivRem(value.Numerator, value.Denominator, out var remainder);
        return remainder.IsZero && !intValue.IsEven;
```

2025-04-06 19:56 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo-netcore.cs
> +            var convertedValue = value.ToDouble();
Yes, I was also surprised by this one, but this is how the `TryConvertToSaturating` is implemented for the `BigInteger`:
```  csharp
            else if (typeof(TOther) == typeof(double))
            {
                double actualResult = (double)value;
                result = (TOther)(object)actualResult;
                return true;
            }
```

I'm not 100% sure of the reasoning, but my guess is that they consider `PositiveInfinity` (being _larger_ than `double.MaxValue`) to be better representation for an overflowing `BigInteger`.

2025-04-06 20:03 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo-netcore.cs
> +    static bool INumberBase<Fraction>.TryConvertToTruncating<TOther>(Fraction value, [MaybeNullWhen(false)] out TOther result) {
Yeah, my guess is that these are only useful to a very small number of people (dealing with hashing or something).

My implementation is based on that of the `BigInteger`- if anyone knows better, let them come forward with a PR 😄

2025-04-06 20:22 UTC, lipchev commented on src/Fractions/Fraction.cs
> +        return fraction.Denominator.IsOne && fraction.Numerator.IsEven;
I'm looking at my other project and that's exactly how I've implemented it there. I've even left myself a little comment:

``` csharp
        // TODO see about first checking the magnitudes
        var quotient = BigInteger.DivRem(numerator, denominator, out var remainder);
        return remainder.IsZero && quotient.IsEven;
```

2025-04-06 20:56 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo.cs
> +                throw new DivideByZeroException();
I wasn't sure whether it's worth the breaking change- my guess is that for the `ToDecimal` people are likely using something like

```  csharp
try
{
  var decimalValue = fraction.ToDecimal();
  // ..
}
catch (DivisionByZero)
{
 //..
}
catch (OverflowException)
{
// ..
}
```

which will still catch the `NaN` or `Infinity` but if we made the same modification on the `ToBigInteger` then the _likely_ `try-catch` scenario will no longer catch the exception:
```  csharp
try
{
  var bigInteger = fraction.ToBigInteger();
  // ..
}
catch (DivisionByZero)
{
 //..
}
```

Of course this is probably not a very likely scenario, but still.. Should i change it (everywhere)?

2025-04-06 22:19 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo.cs
> +            return remainder.IsZero ? 1m / (decimal)decimalPart : 1m / ((decimal)decimalPart + (decimal)remainder / (decimal)numerator);
Fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/9d8553118c56fbbcd419ac945abffcac7a10f47b

2025-04-06 22:19 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo.cs
> +            return remainder.IsZero ? (decimal)withoutDecimalPlaces : (decimal)withoutDecimalPlaces + (decimal)remainder / (decimal)denominator;
Fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/9d8553118c56fbbcd419ac945abffcac7a10f47b

2025-04-06 22:20 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo.cs
> +            return remainder.IsZero ? (decimal)withoutDecimalPlaces : (decimal)withoutDecimalPlaces + (decimal)remainder / (decimal)denominator;
Fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/9d8553118c56fbbcd419ac945abffcac7a10f47b

2025-04-06 22:20 UTC, lipchev commented on src/Fractions/Fraction.ConvertTo.cs
> +            return remainder.IsZero ? 1m / (decimal)decimalPart : 1m / ((decimal)decimalPart + (decimal)remainder / (decimal)numerator);
Fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/9d8553118c56fbbcd419ac945abffcac7a10f47b

2025-04-06 22:29 UTC, lipchev commented on tests/Fractions.Tests/FractionSpecs/Magnitude/Method_MaxMagnitude.cs
> +    }
I agree that as long as everything works, this is cleaner. However, in my experience, as soon as one of the two tests pops up a red label- it becomes much harder to correlate the test values.

2025-04-06 23:44 UTC, lipchev commented on src/Fractions/Fraction.cs
> +#if NET7_0_OR_GREATER
fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/a48dcb56b107395595fb83475a954edf09f43ad9

2025-04-06 23:45 UTC, lipchev commented on src/Fractions/Fraction.cs
> +        return BigInteger.GreatestCommonDivisor(numerator, denominator).IsOne;
fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/1643913092e03ca145a91e4d5de95948f16949da

2025-04-06 23:45 UTC, lipchev commented on src/Fractions/Fraction.cs
> +        return fraction.Denominator.IsOne && fraction.Numerator.IsEven;
fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/1643913092e03ca145a91e4d5de95948f16949da

2025-04-06 23:46 UTC, lipchev commented on src/Fractions/Fraction.cs
> +        return fraction.Denominator.IsOne && !fraction.Numerator.IsEven;
fixed in https://github.com/Fractions-DotNet/Fractions/pull/96/commits/1643913092e03ca145a91e4d5de95948f16949da

2025-04-07 16:46 UTC, danm-de commented on src/Fractions/Fraction.ConvertTo.cs
> +                throw new DivideByZeroException();
Personally, I wouldn't expect a `DivisionByZeroException` to occur during a type conversion. At least not anymore since we support _NaN_ and _+/-Infinity_.

![image](https://github.com/user-attachments/assets/eb89805b-45a4-47f6-9752-cd251843cf1a)

I certainly didn't take into account in the first version that this type of calculation (`x / 0`) takes place within the Convert-methods, and therefore this type of exception is thrown. The usual exceptions for type conversions are `OverflowException`, `NotSupportedException`, etc.

For me, this breaking change would therefore only be logical.

![image](https://github.com/user-attachments/assets/c1a0c867-f73e-4a1c-a729-29369270b1fb)

2025-04-07 16:59 UTC, danm-de approved these changes

2025-04-07 16:59 UTC, merged